//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfAirlineAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class flights
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public flights()
        {
            this.flightEmpoyees = new HashSet<flightEmpoyees>();
            this.Passengers = new HashSet<Passengers>();
        }
    
        public long IDflight { get; set; }
        public string flightNumber { get; set; }
        public System.DateTime departureDate { get; set; }
        public System.TimeSpan departureTime { get; set; }
        public long DepartureAirport { get; set; }
        public long ArrivalAirport { get; set; }
        public System.DateTime ArrivalDate { get; set; }
        public System.TimeSpan ArrivalTime { get; set; }
        public long idAircraft { get; set; }
    
        public virtual Aircrafts Aircrafts { get; set; }
        public virtual Airports Airports { get; set; }
        public virtual Airports Airports1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<flightEmpoyees> flightEmpoyees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Passengers> Passengers { get; set; }
    }
}
