//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfAirlineAPP.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AirlineEntities : DbContext
    {
        public AirlineEntities()
            : base("name=AirlineEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Aboniment> Aboniment { get; set; }
        public virtual DbSet<Adress> Adress { get; set; }
        public virtual DbSet<Aircrafts> Aircrafts { get; set; }
        public virtual DbSet<AirplaneType> AirplaneType { get; set; }
        public virtual DbSet<Airports> Airports { get; set; }
        public virtual DbSet<DanniePersonal> DanniePersonal { get; set; }
        public virtual DbSet<Doljnosti> Doljnosti { get; set; }
        public virtual DbSet<employees> employees { get; set; }
        public virtual DbSet<flights> flights { get; set; }
        public virtual DbSet<flightsClass> flightsClass { get; set; }
        public virtual DbSet<InfoZanitia> InfoZanitia { get; set; }
        public virtual DbSet<InternationalPassportInform> InternationalPassportInform { get; set; }
        public virtual DbSet<JobTitles> JobTitles { get; set; }
        public virtual DbSet<Klient> Klient { get; set; }
        public virtual DbSet<Kolichistvo> Kolichistvo { get; set; }
        public virtual DbSet<Oplata> Oplata { get; set; }
        public virtual DbSet<Passengers> Passengers { get; set; }
        public virtual DbSet<PassengersPersInfo> PassengersPersInfo { get; set; }
        public virtual DbSet<PassportDate> PassportDate { get; set; }
        public virtual DbSet<Polizovateli> Polizovateli { get; set; }
        public virtual DbSet<SposobOplati> SposobOplati { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TipAbonimenta> TipAbonimenta { get; set; }
        public virtual DbSet<Tipzanitia> Tipzanitia { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<VisaInformation> VisaInformation { get; set; }
        public virtual DbSet<Zanitie> Zanitie { get; set; }
        public virtual DbSet<flightEmpoyees> flightEmpoyees { get; set; }
    }
}
