//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfAirlineAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PassengersPersInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PassengersPersInfo()
        {
            this.Passengers = new HashSet<Passengers>();
        }
    
        public long IDPassengerPersonalInfo { get; set; }
        public Nullable<long> PasportDate { get; set; }
        public Nullable<long> InternationalPasportDate { get; set; }
        public string email { get; set; }
        public long PersonAdress { get; set; }
        public string phoneNumber { get; set; }
    
        public virtual InternationalPassportInform InternationalPassportInform { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Passengers> Passengers { get; set; }
        public virtual PassportDate PassportDate { get; set; }
    }
}
