//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfAirlineAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Passengers
    {
        public long IDFlight { get; set; }
        public long IDPassengerPersonalInfo { get; set; }
        public long Class { get; set; }
        public Nullable<bool> baggage { get; set; }
        public Nullable<bool> HandLuggage { get; set; }
    
        public virtual flights flights { get; set; }
        public virtual flightsClass flightsClass { get; set; }
        public virtual PassengersPersInfo PassengersPersInfo { get; set; }
    }
}
