//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfAirlineAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisaInformation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VisaInformation()
        {
            this.InternationalPassportInform = new HashSet<InternationalPassportInform>();
        }
    
        public long VisaID { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Patronymic { get; set; }
        public string gender { get; set; }
        public string citizenshi_ { get; set; }
        public string VisaNumber { get; set; }
        public System.DateTime DateOfIssue { get; set; }
        public System.DateTime ExpirationDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InternationalPassportInform> InternationalPassportInform { get; set; }
    }
}
